- name: upgrade all packages
  yum:
    name: '*'
    state: latest

- name: yum update
  yum:
    name: docker-ce
    state: latest

- name: docker run the image
  docker_container:
    name: hello-world
    image: igorgajsin/smava-test-backend:latest
    state: started
    restart_policy: always
    ports:
      - "8080:8080"
