- name: upgrade all packages
  yum:
    name: '*'
    state: latest

- name: install python-pip
  yum:
    name: python27-pip
    state: latest

- name: pip install docker
  pip:
    name: docker-py

- name: docker run the image
  docker_container:
    name: hello-world
    image: igorgajsin/smava-test-backend:latest
    state: started
    restart_policy: always
    ports:
      - "8080:8080"
