- name: install nginx
  yum:
    name: nginx
    state: latest

- name: copy nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: nginx reload
  service:
    name: nginx
    state: reloaded
